#!/usr/bin/env python3
"""Apply the Cyber Brief Daily v2 design to a built site.

Run AFTER rebuild.py, before pushing:

    python rebuild.py
    python restyle.py            # defaults to ./site
    python restyle.py path/to/site

What it does (idempotent: safe to run more than once):
  1. Writes the new homepage from homepage-static.html, filling the lead story,
     side stories, Latest list and desk counts from the newest articles
  2. Swaps the old header/footer on every other page for the v2 header/footer
  3. Swaps old fonts (Inter, DM Serif, Crimson Text, Roboto Condensed) for
     Geist / Newsreader and the old red for the v2 red
  4. Writes css/theme-v2.css (colour + typography overrides) and links it

Article content is never touched.
"""
import html
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SITE = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "site"
HOMEPAGE = HERE / "homepage-static.html"
SKIP = {"index.html", "index-broadsheet.html"}

FONTS_LINK = ('<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600'
              '&family=Geist+Mono:wght@400;500&family=Newsreader:ital,opsz,wght@0,6..72,400;'
              '0,6..72,500;0,6..72,600;1,6..72,400;1,6..72,600&display=swap" rel="stylesheet">')
FONT_MAP = {
    "DM Serif Display": "Newsreader", "DM Serif Text": "Newsreader", "Crimson Text": "Newsreader",
    "Roboto Condensed": "Geist", "Inter": "Geist",
}
COLOR_MAP = {"#c0392b": "#b8321f", "#e74c3c": "#b8321f"}

OLD_HEADER = re.compile(r'<div class="accent-strip"></div>\s*<header class="site-header">.*?</header>', re.S)
OLD_FOOTER = re.compile(r'<footer class="site-footer">.*?</footer>', re.S)
V2_HEADER = re.compile(r'<!-- cbd-v2:header -->.*?<!-- /cbd-v2:header -->', re.S)
V2_FOOTER = re.compile(r'<!-- cbd-v2:footer -->.*?<!-- /cbd-v2:footer -->', re.S)
OLD_FONTS = re.compile(r'<link href="https://fonts\.googleapis\.com/css2\?family=Crimson\+Text[^"]*" rel="stylesheet">')

THEME_CSS = """/* Cyber Brief Daily v2 theme, generated by restyle.py. Loaded after style.css. */
:root, body.dark {
  --bg: #f5f3ee; --bg-alt: #ece9e1; --surface: #f5f3ee;
  --text: #17171a; --text-secondary: #4a4843; --muted: #5c5a55;
  --accent: #b8321f; --accent-90: #9e2a1a;
  --accent-light: rgba(184, 50, 31, 0.06); --accent-glow: rgba(184, 50, 31, 0.12);
  --border: #d6d2c8; --border-light: #e6e2d8; --nav-bg: #f5f3ee; --header-border: #17171a;
  --footer-bg: #17171a; --footer-text: #d9d5cc; --footer-muted: #8d8a83;
  --radius: 0px; --card-shadow: none; --card-shadow-hover: none; --img-brightness: 1;
}
body { background: #f5f3ee; color: #17171a; font-family: 'Geist', system-ui, sans-serif; -webkit-font-smoothing: antialiased; }
h1, h2, h3, h4, .section-title, .conf-name, .gloss-letter {
  font-family: 'Newsreader', serif !important; font-weight: 500; letter-spacing: -0.01em; text-wrap: balance;
}
h1 { font-weight: 500 !important; letter-spacing: -0.02em; }
.section-title { font-weight: 600; font-style: normal; }
.cat-label, .cat-label-sm, .article-date, .card-meta, .article-cats a {
  font-family: 'Geist Mono', monospace; letter-spacing: 0.04em;
}
.cat-label, .cat-label-sm { color: #b8321f; text-transform: uppercase; font-size: 11px; background: none; }
.card, .card:hover { box-shadow: none; border-radius: 0; }
.reading-progress { background: #b8321f; }
.cbd-chrome a { color: inherit; text-decoration: none; }
.cbd-chrome a:hover { color: #b8321f; }
.cbd-chrome .cbd-light a:hover { color: #fff; }
"""

TODAY_JS = ("<script>(function(){var t=document.getElementById('today');if(t)t.textContent=new Date()"
            ".toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});})();</script>")


def chrome_from_homepage(home: str):
    """Cut the header and footer out of the homepage so every page stays in sync with it."""
    start = home.index("<!-- Utility bar -->")
    end = home.index("</header>", start) + len("</header>")
    header = home[start:end]
    footer = re.search(r"<footer.*?</footer>", home, re.S).group(0)
    # links that only resolve on the homepage
    header = header.replace('href="#newsletter"', 'href="https://cyberbriefdaily.com/#newsletter"')
    # slightly smaller masthead on inner pages
    header = header.replace("font-size:clamp(40px,6vw,68px)", "font-size:clamp(34px,4.6vw,52px)")
    header = (f'<!-- cbd-v2:header --><div class="cbd-chrome" id="top" style="font-family:\'Geist\',system-ui,sans-serif">'
              f'{header}</div>{TODAY_JS}<!-- /cbd-v2:header -->')
    footer = (f'<!-- cbd-v2:footer --><div class="cbd-chrome" style="font-family:\'Geist\',system-ui,sans-serif;margin-top:56px">'
              f'{footer}</div><!-- /cbd-v2:footer -->')
    return header, footer


# ---------------------------------------------------------------- homepage
# Front page, Latest list, Desk counts and the Latest JSON-LD are rebuilt from
# the articles on every run. The Brief, Most read and the Report module are
# editorial picks: edit them directly in homepage-static.html.

DESKS = {  # filter label -> article keywords that count toward it
    "News": {"News"},
    "AI": {"AI", "Agentic AI", "AI Security", "Artificial Intelligence", "AI Regulation"},
    "Ransomware": {"Ransomware"},
    "Data Breaches": {"Data Breaches", "Data Breach"},
    "Cybercrime": {"Cybercrime", "Fraud", "Espionage", "Sextortion", "Phishing"},
    "Geopolitics": {"Geopolitics", "Nation-State Threats", "Nation State", "North Korea", "Critical Infrastructure"},
    "Policy": {"Policy & Regulation", "Policy", "Regulation", "AI Regulation", "Government", "Compliance", "Legal"},
}
DESK_PAGES = [("News", "news"), ("Data Breaches", "data-breaches"), ("Cybercrime", "cybercrime"),
              ("Geopolitics", "geopolitics"), ("AI", "ai"), ("Ransomware", "ransomware"),
              ("Policy & Regulation", "policy-and-regulation"), ("Healthcare", "healthcare")]
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()
ROOT = "https://cyberbriefdaily.com"


def _dek(desc: str) -> str:
    """build.py truncates descriptions at ~160 chars; end them on a sentence or a word."""
    desc = html.unescape(desc).strip()
    if not desc or desc[-1] in ".!?\"'”’":
        return desc
    cut = max(desc.rfind(". "), desc.rfind("? "), desc.rfind("! "))
    if cut > 60:
        return desc[:cut + 1]
    return desc.rsplit(" ", 1)[0].rstrip(",;:-–—") + "…"


def load_articles(site: Path):
    out = []
    for p in (site / "articles").glob("*.html"):
        s = p.read_text(encoding="utf-8")
        m = re.search(r'<script type="application/ld\+json">(.*?)</script>', s, re.S)
        try:
            ld = json.loads(m.group(1)) if m else {}
        except ValueError:
            continue
        date = ld.get("datePublished", "")
        if ld.get("@type") != "NewsArticle" or not re.match(r"\d{4}-\d\d-\d\d", date):
            continue  # undated legacy imports never reach the front page
        kw = [k.strip() for k in ld.get("keywords", "").split(",") if k.strip()]
        y, mo, d = int(date[:4]), int(date[5:7]), int(date[8:10])
        mins = re.search(r"(\d+) min read", s)
        out.append({
            "url": f"{ROOT}/articles/{p.name}", "date": date,
            "short": f"{d:02d} {MONTHS[mo - 1]}", "long": f"{d} {MONTHS[mo - 1]} {y}",
            "title": html.unescape(ld.get("headline", "")).strip(),
            "dek": _dek(ld.get("description", "")),
            "author": (ld.get("author") or {}).get("name", "Cyber Brief Daily"),
            "cat": ld.get("articleSection") or (kw[0] if kw else "News"),
            "kw": kw, "image": ld.get("image", ""),
            "read": f"{mins.group(1)} min read" if mins else "",
            "desks": [name for name, keys in DESKS.items() if keys & set(kw)],
        })
    out.sort(key=lambda a: a["date"], reverse=True)
    return out


MONO = "font-family:'Geist Mono',monospace;font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#b8321f"


def _hero(a):
    e = html.escape
    second = next((k for k in a["kw"] if k not in (a["cat"], "News")), "")
    img = (f'<a href="{a["url"]}" style="display:block;aspect-ratio:16/9;overflow:hidden;background:#e6e2d8">'
           f'<img src="{e(a["image"])}" alt="{e(a["title"])}" style="width:100%;height:100%;object-fit:cover;display:block"></a>'
           if a["image"] else "")
    meta = [f'<span style="color:#17171a;font-weight:500">{e(a["author"])}</span>', f'<span>{a["long"]}</span>']
    if a["read"]:
        meta.append(f'<span>{a["read"]}</span>')
    return f"""<article style="flex:2 1 520px;min-width:0;padding-right:32px;display:flex;flex-direction:column;gap:18px">
    {img}
    <div style="display:flex;gap:12px;align-items:center;font-family:'Geist Mono',monospace;font-size:11.5px;text-transform:uppercase;letter-spacing:0.06em">
      <span style="color:#b8321f;font-weight:500">{e(a["cat"])}</span>
      <span style="color:#8d8a83">{e(second)}</span>
    </div>
    <h1 style="margin:0;font-family:'Newsreader',serif;font-weight:500;font-size:clamp(34px,4.2vw,52px);line-height:1.02;letter-spacing:-0.02em;text-wrap:balance"><a href="{a["url"]}">{e(a["title"])}</a></h1>
    <p style="margin:0;font-family:'Newsreader',serif;font-size:20px;line-height:1.45;color:#3a3935;max-width:62ch;text-wrap:pretty">{e(a["dek"])}</p>
    <div style="display:flex;gap:10px;align-items:center;font-size:13px;color:#5c5a55">
      {'<span>·</span>'.join(meta)}
    </div>
  </article>"""


def _side(items):
    e = html.escape
    pads = ["padding-bottom:22px;border-bottom:1px solid #d6d2c8", "padding:22px 0;border-bottom:1px solid #d6d2c8", "padding-top:22px"]
    rows = []
    for a, pad in zip(items, pads):
        dek = f'\n      <p style="margin:0;font-size:14.5px;line-height:1.5;color:#4a4843">{e(a["dek"])}</p>' if a["dek"] and pad != pads[2] else ""
        rows.append(f"""    <article style="{pad};display:flex;flex-direction:column;gap:10px">
      <span style="{MONO}">{e(a["cat"])}</span>
      <h2 style="margin:0;font-family:'Newsreader',serif;font-weight:500;font-size:25px;line-height:1.12;letter-spacing:-0.01em;text-wrap:balance"><a href="{a["url"]}">{e(a["title"])}</a></h2>{dek}
      <span style="font-size:12.5px;color:#5c5a55">{e(a["author"])} · {a["short"]}</span>
    </article>""")
    return "\n".join(rows)


def _latest(pool):
    """Every row that is in the top 8 of at least one filter; data-show lists those filters."""
    e = html.escape
    show = {}
    for f in ["All"] + list(DESKS):
        for a in [a for a in pool if f == "All" or f in a["desks"]][:8]:
            show.setdefault(a["url"], []).append(f)
    rows = []
    for a in pool:
        if a["url"] not in show:
            continue
        hidden = "" if "All" in show[a["url"]] else " hidden"
        rows.append(f"""<article data-show="|{'|'.join(show[a['url']])}|"{hidden} style="display:grid;grid-template-columns:84px minmax(0,1fr);gap:20px;padding:20px 0;border-bottom:1px solid #d6d2c8">
          <div style="display:flex;flex-direction:column;gap:4px;font-family:'Geist Mono',monospace;font-size:11.5px;color:#5c5a55;padding-top:5px">
            <span style="color:#17171a">{a["short"]}</span>
          </div>
          <div style="display:flex;flex-direction:column;gap:7px">
            <span style="{MONO}">{e(a["cat"])}</span>
            <h3 style="margin:0;font-family:'Newsreader',serif;font-weight:500;font-size:23px;line-height:1.15;letter-spacing:-0.01em;text-wrap:balance"><a href="{a["url"]}">{e(a["title"])}</a></h3>
            <p style="margin:0;font-size:14.5px;line-height:1.5;color:#4a4843;max-width:68ch;text-wrap:pretty">{e(a["dek"])}</p>
            <span style="font-size:12.5px;color:#5c5a55">{e(a["author"])}</span>
          </div>
        </article>""")
    return "\n".join(rows)


def build_homepage(site: Path, home: str) -> str:
    arts = load_articles(site)
    if len(arts) < 12:
        print(f"  homepage: only {len(arts)} dated articles found, keeping the template as-is")
        return home
    hero, side, rest = arts[0], arts[1:4], arts[4:]

    home = re.sub(r'<article style="flex:2 1 520px.*?</article>', lambda _: _hero(hero), home, count=1, flags=re.S)
    home = re.sub(r'(<div style="flex:1 1 260px;min-width:0;padding:0 28px[^"]*">).*?(</div>\s*<aside)',
                  lambda m: m.group(1) + "\n" + _side(side) + "\n  " + m.group(2), home, count=1, flags=re.S)
    home = re.sub(r'(<section data-screen-label="Latest".*?<div style="display:flex;flex-direction:column">).*?'
                  r'(</div>\s*<a href="https://cyberbriefdaily\.com/categories/news\.html" style="display:inline-flex)',
                  lambda m: m.group(1) + "\n" + _latest(rest) + "\n    " + m.group(2), home, count=1, flags=re.S)

    # desk counts, straight from the category pages
    for name, slug in DESK_PAGES:
        cat = site / "categories" / f"{slug}.html"
        m = re.search(r'class="cat-count-text">(\d+)', cat.read_text(encoding="utf-8")) if cat.exists() else None
        if m:
            home = re.sub(rf'(<span>{re.escape(html.escape(name))}</span><span[^>]*>)\d+(</span>)',
                          lambda x: x.group(1) + m.group(1) + x.group(2), home)

    # social image + structured data follow the lead story
    if hero["image"]:
        home = re.sub(r'(<meta (?:property="og:image"|name="twitter:image") content=")[^"]*', lambda m: m.group(1) + hero["image"], home)
        home = re.sub(r'(<link rel="preload" as="image" href=")[^"]*', lambda m: m.group(1) + hero["image"], home)
    items = [{"@type": "ListItem", "position": i + 1, "url": a["url"], "name": a["title"]} for i, a in enumerate(arts[:8])]
    def fix_ld(m):
        ld = json.loads(m.group(1))
        for node in ld.get("@graph", []):
            if node.get("@type") == "ItemList":
                node["itemListElement"] = items
        return f'<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>'
    home = re.sub(r'<script type="application/ld\+json">(.*?)</script>', fix_ld, home, count=1, flags=re.S)

    # filter script: rows carry the filters they belong to
    home = re.sub(r"rows=document\.querySelectorAll\('article\[data-desk\]'\)", "rows=document.querySelectorAll('article[data-show]')", home)
    home = re.sub(r"r\.hidden = f==='All' \? \+r\.getAttribute\('data-rank'\)>=8 : r\.getAttribute\('data-desk'\)!==f;",
                  "r.hidden = r.getAttribute('data-show').indexOf('|'+f+'|')<0;", home)
    print(f"  homepage: lead = {hero['title']!r} ({hero['long']})")
    return home


def swap_fonts_and_colors(text: str) -> str:
    for old, new in FONT_MAP.items():
        text = re.sub(rf"""(['"]){re.escape(old)}\1""", rf"\1{new}\1", text)
    for old, new in COLOR_MAP.items():
        text = re.sub(re.escape(old), new, text, flags=re.I)
    return text


def restyle_page(path: Path, header: str, footer: str) -> bool:
    s = path.read_text(encoding="utf-8")
    orig = s
    s = V2_HEADER.sub(lambda _: header, s) if V2_HEADER.search(s) else OLD_HEADER.sub(lambda _: header, s, count=1)
    s = V2_FOOTER.sub(lambda _: footer, s) if V2_FOOTER.search(s) else OLD_FOOTER.sub(lambda _: footer, s, count=1)
    s = OLD_FONTS.sub(FONTS_LINK, s)
    prefix = "../" * (len(path.relative_to(SITE).parts) - 1) or "./"
    theme = f'<link rel="stylesheet" href="{prefix}css/theme-v2.css">'
    if "css/theme-v2.css" not in s:
        s = re.sub(r'(<link rel="stylesheet" href="[^"]*css/style\.css">)', lambda m: m.group(1) + "\n" + theme, s, count=1)
    # page-level <style> blocks
    s = re.sub(r"<style>.*?</style>", lambda m: swap_fonts_and_colors(m.group(0)), s, flags=re.S)
    if s != orig:
        path.write_text(s, encoding="utf-8", newline="\n")
        return True
    return False


def main():
    if not (SITE / "css" / "style.css").exists():
        sys.exit(f"Not a built site: {SITE}")
    home = HOMEPAGE.read_text(encoding="utf-8")
    header, footer = chrome_from_homepage(home)

    (SITE / "index.html").write_text(build_homepage(SITE, home), encoding="utf-8", newline="\n")

    css = SITE / "css" / "style.css"
    css.write_text(swap_fonts_and_colors(css.read_text(encoding="utf-8")), encoding="utf-8", newline="\n")
    (SITE / "css" / "theme-v2.css").write_text(THEME_CSS, encoding="utf-8", newline="\n")

    pages = [p for p in SITE.rglob("*.html")
             if p.relative_to(SITE).as_posix() not in SKIP
             and not any(part.startswith(".") for part in p.relative_to(SITE).parts)]
    changed = sum(restyle_page(p, header, footer) for p in pages)
    missing = [p.relative_to(SITE).as_posix() for p in pages if "cbd-v2:header" not in p.read_text(encoding="utf-8")]
    print(f"restyle: homepage restored, {changed}/{len(pages)} pages updated")
    if missing:
        print(f"  WARNING: {len(missing)} pages have no recognisable header: {missing[:5]}")


if __name__ == "__main__":
    main()
